### ISSUE TITLE
Check existing docs on MIME types/ file extension settings

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp#271]
With the RFC: [Make upload mime validation part of core recipe](https://github.com/silverstripe/silverstripe-framework/issues/8782) the following module has become a direct dependancy of CMS core: https://github.com/silverstripe/silverstripe-mimevalidator

silverstripe-mimevalidator has been for a longtime a direct dependancy of this cwp/cwp module. It's assumed that the majority of updates in this module have been handled through the changes in the RFC issue, but I'm raising this to confirm that any existing related documentation on cwp.govt.nz is also reviewed and updated if necessary.

Any documentation held in the following section (https://www.cwp.govt.nz/developer-docs) is managed via this repo, here: https://github.com/silverstripe/cwp/tree/2/docs/en

Note: be sure to merge any changes up to the `master` branch to ensure they're picked up by the cronjob and published on the website.

Things to check/ document:
- confirm that any existing related documentation on cwp.govt.nz is also reviewed and updated if necessary.
- in the changelog note: if users opted-out of mimevalidator module (cwp-recipe-core), they should consider manually disable it now through configuration settings, as it will be installed on upgrade through core recipes.
- in the changelog note: when CWP sites upgrade they'll see a redundant config file (replacing the CWP-specific config file). If they've tweaked this, they'll just want to delete the new file

### Subtasks
 - [x] Changelogs
   - [x] CMS
   - [x] CWP
 - [x] Documentation
   - [x] Module
   - [x] CMS
   - [x] CWP
 - [x] merge-up CWP `2.6` -> `2` -> `master`

### PRs
 - [x] https://github.com/silverstripe/silverstripe-mimevalidator/pull/40
 - [x] https://github.com/silverstripe/cwp/pull/281

**Comment by brynwhyman** [comment]
Maybe this? https://www.cwp.govt.nz/developer-docs/en/2/how_tos/adding_an_allowed_extension/

**Comment by dnsl48** [comment]
Might worth mentioning in [2.6.0 changelog](https://github.com/silverstripe/cwp/blob/2.6/docs/en/05_Releases_and_changelogs/cwp_2.6.0.md), that if users opted-out of mimevalidator module (cwp-recipe-core), they should consider manually disable it now through configuration settings, as it will be installed on upgrade through core recipes.
